sources:
  # Queensland Fire Department
  qfd:
    uri: "https://publiccontent-gis-psba-qld-gov-au.s3.amazonaws.com/content/Feeds/BushfireCurrentIncidents/bushfireAlert_capau.xml"
    tagregex:
      - field: headline
        regex: "^([A-Z ]+)?(?: \\((HAZARD REDUCTION BURN)\\))?(?:[A-Za-z ]+)? - ([^()-]+)(?: +\\((?:near )?(.+)\\))?(?: - Multiple Warnings)? - fire as at.*$"
        tags:
          - template: '{{tag}}'
            category: Instruction
          - template: '{{tag}}'
            category: IncidentType
          - template: '{{tag}} Qld'
            transform: 'tag.replace(" and ", ", ").split(", ")'
            category: Location
          - template: '{{tag}} Qld'
            category: Location

    post_template: |
      {{headline}} ({{identifier}}) {{tags.iter("Instruction") | join(" ")}} {{tags.iter("Location") | join(" ")}} #QLDFire #BushfireWarning

      See https://www.fire.qld.gov.au/Current-Incidents for official warnings from the QFD.  DO NOT RELY ON THIS SERVICE FOR TIMELY EMERGENCY WARNINGS.

      Location: {{parameters["Location"]}}
      Map: https://www.openstreetmap.org/#map=14/{{position[0]}}/{{position[1]}}
      Incident Type: {{parameters["IncidentType"]}}
      Alert Level: {{parameters["AlertLevel"]}}
      Severity: {{severity}}
      Action: {{responseType}}
      Expires: {{expires}}

      {{description}}

      {{instruction}}

      - See https://help.abc.net.au/hc/en-us/articles/5896732505103-How-can-I-find-ABC-TV-and-radio-frequencies-in-my-area for a listing of ABC Local Radio stations which may be broadcasting emergency information in your area.

min_severity_level: Moderate

styles:
  _DEFAULT_:
    color: "#ccccccff"
    fill_color: "#cccccc3f"
    width: 2
  severity:
    Extreme:
      color: "#ff0000ff"
      fill_color: "#ff00003f"
      width: 2
    Severe:
      color: "#ffcc00ff"
      fill_color: "#ffcc003f"
      width: 2
    Moderate:
      color: "#ffff00ff"
      fill_color: "#ffff003f"
      width: 2
    Minor:
      color: "#ccff00ff"
      fill_color: "#ccff003f"
      width: 2

map_size:
  width: 800
  height: 500

zoom_levels:
  - auto
  - 6
  - 10
  - 14

status_db: status.db

mastodon:
  access_token: Insert Your Token Here
  api_base_url: https://mastodon.example.com
