sources:
  qfes: "https://publiccontent-gis-psba-qld-gov-au.s3.amazonaws.com/content/Feeds/BushfireCurrentIncidents/bushfireAlert_capau.xml"

status_db: status.db

styles:
  _DEFAULT_:
    color: "#ccccccff"
    fill_color: "#cccccc3f"
    width: 2
  severity:
    Extreme:
      color: "#ff0000ff"
      fill_color: "#ff00003f"
      width: 2
    Severe:
      color: "#ffcc00ff"
      fill_color: "#ffcc003f"
      width: 2
    Moderate:
      color: "#ffff00ff"
      fill_color: "#ffff003f"
      width: 2
    Minor:
      color: "#ccff00ff"
      fill_color: "#ccff003f"
      width: 2

map_size:
  width: 800
  height: 500

zoom_levels:
  - auto
  - 8
  - 12
  - 16

mastodon:
  access_token: Insert Your Token Here
  api_base_url: https://mastodon.example.com

post_template: |
  DISCLAIMER: This is an unofficial and experimental service run by a third party.
  See https://www.fire.qld.gov.au/Current-Incidents for official warnings from
  the QFES.  DO NOT RELY ON THIS SERVICE FOR TIMELY EMERGENCY WARNINGS.

  {{headline}} ({{identifier}})
  Severity: {{severity}} Action: {{responseType}}
  Expires: {{expires}}

  {{description}}

  {{instruction}}

  #BushfireWarning #{{grid}}
